name: TestPlugin
main: io.github.nickacpt.iicptinwgcwypnttass.testplugin.TestPlugin
version: 1.0
api-version: 1.17

commands:
  testgui:
    description: A command to test the generated guis
  testgui2:
    description: A command to test the generated guis